version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: club_futbol
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - club_network
networks:
  club_network:
volumes:
  db_data:
