# docker-compose.yml
version: '3.8'
services:
  db_fpi:
    image: postgres
    ports:
      - "5442:5432"
    restart: always
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
    volumes:
      - fpidata:/var/lib/postgresql/data

volumes:
  fpidata:
